---
title: "Capstone"
author: "Katie Osadczuk"
date: "2023-10-02"
output:
  html_document: 
    theme: flatly
    highlight: zenburn
    code_folding: show
    toc: yes
    toc_float: yes
    code_download: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Libraries

```{r}
library(corrplot)
library(tidyverse)
library(dplyr)
library(Sleuth3)
library(mosaic)
library(stats)
library(gmodels)
library(agricolae)
library(multcomp)
library(pairwiseCI)
library(ggplot2)
library(ISLR)
library(olsrr)
library(ProbBayes)
library(bayesrules)
library(bayesplot)
library(janitor)
library(rstan)
library(broom.mixed)
library(rstanarm)
library(tidybayes)
library(gridExtra)
```

# Data

```{r}
Election_Results = read.csv("2020-election-results.csv", sep=",")
GDP = read.csv("gdp-by-state-[updated-april-2023].csv", sep=",")
Gun_Ownership = read.csv("gun-ownership-by-state-[updated-april-2023].csv", sep=",")
  Poverty_Rate = read.csv("poverty-rate-by-state-[updated-september-2023].csv", sep=",")
Population = read.csv("state-population-table.csv", sep=",")
Suicide_Rates = read.csv("suicide-rates-by-state-[updated-april-2023].csv", sep=",")
Ethnicity = read.csv("table-data.csv", sep=",")
```

```{r}
Election_Results2 = column_to_rownames(Election_Results, var = "state")
Election_Results3 = Election_Results2[!(row.names(Election_Results2) %in% c("District of Columbia")), ]
GDP2 = column_to_rownames(GDP, var = "state")
GDP3 = GDP2[!(row.names(GDP2) %in% c("District of Columbia")), ]
Gun_Ownership2 = column_to_rownames(Gun_Ownership, var = "state")
Poverty_Rate2 = column_to_rownames(Poverty_Rate, var = "state")
Poverty_Rate3 = Poverty_Rate2[!(row.names(Poverty_Rate2) %in% c("District of Columbia")), ]
Population2 = column_to_rownames(Population, var = "state")
Suicide_Rates2 = column_to_rownames(Suicide_Rates, var = "state")
Ethnicity2 = column_to_rownames(Ethnicity, var = "State")
Ethnicity3 = Ethnicity2[!(row.names(Ethnicity2) %in% c("District of Columbia", "Puerto Rico")), ]
```

```{r}
States = cbind(Election_Results3, GDP3, Gun_Ownership2, Poverty_Rate3, Population2, Suicide_Rates2, Ethnicity3)

States2 = subset(States, select=c('percD', 'percR', 'gdpPerCapita2022', 'pop2023', 'WhiteTotalPerc', 'BlackTotalPerc', 'IndianTotalPerc', 'AsianTotalPerc', 'HawaiianTotalPerc', 'OtherTotalPerc', 'gunOwnershipPercentage', 'densityMi', 'growthRate', 'percentOfPopulationBelowPovertyLevel', 'suicideRate'))

colnames(States2)
colnames(States2) <- c("Dem", "R", "GDP", "P", "W", "B", "NA1", "A", "H", "O", "GO", "D", "GR", "PL", "SR")
colnames(States2)
States2 
```

# Exploratory Analysis

## Correlation

```{r}
cor(States2)
corrplot(cor(States2), type = "upper")
```

## Election Results

```{r}
States3 = States2
States3$Dem = States2$Dem * 100
States3$R = States2$R * 100

g1 = ggplot(States3, aes(y = SR, x = Dem))  + 
  geom_point(alpha = .1) +
  xlab("Dem") +
  ylab("SR") +
  ggtitle("SR vs Dem") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_continuous(expand = c(0, 0), limits = c(0, 75)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g2 = ggplot(States3, aes(y = SR, x = R))  + 
  geom_point(alpha = .1) +
  xlab("R") +
  ylab("SR") +
  ggtitle("SR vs R") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 75)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

grid.arrange(g1, g2, ncol = 2, nrow = 2)
```

## Stats

```{r}
States3$GDP = States2$GDP / 1000
States3$P = States2$P / 1000000
States3$GR = States2$GR * 100

g3 = ggplot(States3, aes(y = SR, x = GDP))  + 
  geom_point(alpha = .1) +
  xlab("GDP") +
  ylab("SR") +
  ggtitle("SR VS GDP") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 100)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g4 = ggplot(States3, aes(y = SR, x = P))  + 
  geom_point(alpha = .1) +
  xlab("P") +
  ylab("SR") +
  ggtitle("SR VS P") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", formula = y ~ log(x), se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 40)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g5 = ggplot(States3, aes(y = SR, x = GO))  + 
  geom_point(alpha = .1) +
  xlab("GO") +
  ylab("SR") +
  ggtitle("SR VS GO") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 70)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g6 = ggplot(States3, aes(y = SR, x = D))  + 
  geom_point(alpha = .1) +
  xlab("D") +
  ylab("SR") +
  ggtitle("SR VS D") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", formula = y ~ log(x), se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1300)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g7 = ggplot(States3, aes(y = SR, x = PL))  + 
  geom_point(alpha = .1) +
  xlab("PL") +
  ylab("SR") +
  ggtitle("SR VS PL") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 20)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g8 = ggplot(States3, aes(y = SR, x = GR))  + 
  geom_point(alpha = .1) +
  xlab("GR") +
  ylab("SR") +
  ggtitle("SR VS GR") +
  geom_point(color='darkblue') +
  stat_smooth(method = "lm", se = FALSE) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(-2, 2)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

grid.arrange(g3, g4, g5, g6, g7, g8, ncol = 3, nrow = 2)
```

## Ethnicities

```{r}
States3$W = States2$W * 100
States3$B = States2$B * 100
States3$NA1 = States2$NA1 * 100
States3$A = States2$A * 100
States3$H = States2$H * 100
States3$O = States2$O * 100

g9 = ggplot(States3, aes(y = SR, x = W))  + 
  geom_point(alpha = .1) +
  xlab("W") +
  ylab("SR") +
  ggtitle("SR VS W") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 100)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g10 = ggplot(States3, aes(y = SR, x = B))  + 
  geom_point(alpha = .1) +
  xlab("B") +
  ylab("SR") +
  ggtitle("SR VS B") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 40)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g11 = ggplot(States3, aes(y = SR, x = States3$NA1))  + 
  geom_point(alpha = .1) +
  xlab("NA") +
  ylab("SR") +
  ggtitle("SR VS NA") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 15)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

States3

g12 = ggplot(States3, aes(y = SR, x = A))  + 
  geom_point(alpha = .1) +
  xlab("A") +
  ylab("SR") +
  ggtitle("SR VS A") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 40)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g13 = ggplot(States3, aes(y = SR, x = H))  + 
  geom_point(alpha = .1) +
  xlab("H") +
  ylab("SR") +
  ggtitle("SR VS H") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 12.5)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

g14 = ggplot(States3, aes(y = SR, x = O))  + 
  geom_point(alpha = .1) +
  xlab("O") +
  ylab("SR") +
  ggtitle("SR VS O") +
  geom_point(color='darkblue') +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 30)) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 35))

grid.arrange(g9, g10, g11, g12, g13, g14, ncol = 3, nrow = 2)
```

# Linear Model

## Full

```{r}
fullstates_lm <- lm(SR ~ ., data = States3)
summary(fullstates_lm)
fullstates_lm$coefficients
```

## Minimum

```{r}
minstates_lm <- lm(SR ~ GO + PL , data = States3)
summary(minstates_lm)
minstates_lm$coefficients
```

## All varaibles ols

```{r}
states_forward = ols_step_forward_aic(fullstates_lm)
states_forward
plot(states_forward)

states_back = ols_step_backward_aic(fullstates_lm)
states_back
plot(states_back)

states_forward$model
states_back$model

states_lm2 <- lm(SR ~ PL + GO + Dem + R + GR, data = States3)
summary(states_lm2)
states_lm2$coefficients

statesFINAL <- lm(SR ~ PL + GO + R + GR, data = States3)
```

## Linear Model with Yes/No Variable

```{r}
States4 = subset(States3, select=c('GDP', 'P', 'W', 'B', 'NA1', 'A', 'H', 'O', 'GO', 'D', 'GR', 'PL', 'SR'))
States4$party <- States$win
States4$party <- as.factor(States4$party)
str(States4)
```

```{r}
ggplot(States4, aes(y = SR, x = party, color = party))  + 
  geom_boxplot() +
  xlab("Party") +
  ylab("SR") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("SR VS Party") +
  labs(color = "Party") 
```

```{r}
states_lm3 <- lm(SR ~ ., data = States4)
summary(states_lm3)
states_lm3$coefficients

states_forward1 = ols_step_forward_aic(states_lm3)
states_forward1
plot(states_forward1)

states_forward1$model
```

```{r}
stateslm4 <- lm(SR ~ GO + PL + GR + R + O + NA1, data = States3)
summary(stateslm4)
states_lm4$coefficients
```

# Bayes Model

```{r}
statesbayes <- stan_glm(
  SR ~ GO + PL + GR + R + O + NA1, data = States3, 
  family = gaussian,
  chains = 4, iter = 5000*2, seed = 84735)
```

```{r}
mcmc_trace(statesbayes, size = 0.1)
mcmc_dens_overlay(statesbayes)
mcmc_acf(statesbayes)
neff_ratio(statesbayes)
rhat(statesbayes)
```

```{r}
truesr <- States2$suicideRate
truesr

predictedlm <- predict(statesFINAL, type="response")
predictedlm

truesr - predictedlm

predictedbayes <- predict(statesbayes, type="response")
predictedbayes
```

```{r}
mlm = mean((abs(truesr - predictedlm)))
sdlm = sd((abs(truesr - predictedlm)))
mb = mean((abs(truesr - predictedbayes)))
sdb = sd((abs(truesr - predictedbayes)))

mlm
sdlm
mb
sdb

(mlm-mb)/mb * 100
(sdlm-sdb)/sdb * 100

```
